name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    
env:
  DOCKERHUB_USERNAME: sornian

jobs:

  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file android.Dockerfile --tag v8:$(date +%s)
    - name: Publish the docker image
        run: |
          docker login --username ${{ env.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
          docker push sornian/v8
